// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTmC6Jo0E0RF7KBDkh-gCfRxRgoON4_LY',
    appId: '1:1035801497353:web:e329b142d7fd0e40594dd8',
    messagingSenderId: '1035801497353',
    projectId: 'shophub-e06fc',
    authDomain: 'shophub-e06fc.firebaseapp.com',
    storageBucket: 'shophub-e06fc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb_hzHCRAWoP7NHvwdojKkGHp18ZbLjRs',
    appId: '1:1035801497353:android:d869f0b2a14bf920594dd8',
    messagingSenderId: '1035801497353',
    projectId: 'shophub-e06fc',
    storageBucket: 'shophub-e06fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjzF40sVhqgtzii5XqIa73OupopgEqzUQ',
    appId: '1:1035801497353:ios:41e4a1614ac676b1594dd8',
    messagingSenderId: '1035801497353',
    projectId: 'shophub-e06fc',
    storageBucket: 'shophub-e06fc.firebasestorage.app',
    androidClientId: '1035801497353-6qdg106g9u8jsshpm9v6h3432e7llq12.apps.googleusercontent.com',
    iosClientId: '1035801497353-79i0qcoi4dbp8rgobsaoith67iorfibn.apps.googleusercontent.com',
    iosBundleId: 'com.example.shobhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjzF40sVhqgtzii5XqIa73OupopgEqzUQ',
    appId: '1:1035801497353:ios:41e4a1614ac676b1594dd8',
    messagingSenderId: '1035801497353',
    projectId: 'shophub-e06fc',
    storageBucket: 'shophub-e06fc.firebasestorage.app',
    androidClientId: '1035801497353-6qdg106g9u8jsshpm9v6h3432e7llq12.apps.googleusercontent.com',
    iosClientId: '1035801497353-79i0qcoi4dbp8rgobsaoith67iorfibn.apps.googleusercontent.com',
    iosBundleId: 'com.example.shobhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTmC6Jo0E0RF7KBDkh-gCfRxRgoON4_LY',
    appId: '1:1035801497353:web:3ea090abe494d5c7594dd8',
    messagingSenderId: '1035801497353',
    projectId: 'shophub-e06fc',
    authDomain: 'shophub-e06fc.firebaseapp.com',
    storageBucket: 'shophub-e06fc.firebasestorage.app',
  );

}